import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error('Supabase URL or Key is missing. Please check your .env file.');
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const initialProducts = [
    {
        name: "Cotton T-shirt",
        brand: "Lifestyle",
        material: "Pima Cotton",
        price: 840,
        originalPrice: 5600,
        condition: "Like New",
        image: "/assets/woman - tshirt1.jpg",
        category: "For Her",
    },
    {
        name: "Short T-Shirt",
        brand: "H&M",
        material: "Polyester + Cotton",
        price: 600,
        originalPrice: 12000,
        condition: "Excellent",
        image: "/assets/woman - tshirt.jpg",
        category: "For Her",
    },
    {
        name: "Baggy Jeans",
        brand: "Levi's",
        material: "Organic Denim",
        price: 940,
        originalPrice: 9600,
        condition: "Like New",
        image: "/assets/men - baggy jeans.jpg",
        category: "For Him",
    },
    {
        name: "Merino Wool Scarf",
        brand: "Zara",
        material: "Merino Wool",
        price: 480,
        originalPrice: 7200,
        condition: "Excellent",
        image: "/assets/clothes.jpg",
        category: "Accessories",
    },
    {
        name: "Linen Shirt",
        brand: "Marks & Spencer",
        material: "100% Linen",
        price: 840,
        originalPrice: 11200,
        condition: "Like New",
        image: "/assets/men - linen.jpg",
        category: "For Him",
    },
    {
        name: "Polo T-shirt",
        brand: "Ralph Lauren",
        material: "Organic Cotton",
        price: 660,
        originalPrice: 15200,
        condition: "Like New",
        image: "/assets/men - polos.jpg",
        category: "For Him",
    },
    {
        name: "Black Track Pants",
        brand: "Adidas",
        material: "Cotton + Polyester",
        price: 600,
        originalPrice: 8800,
        condition: "Good",
        image: "/assets/men - trousers.jpg",
        category: "For Him",
    },
    {
        name: "Cotton Polo Sweater",
        brand: "Uniqlo",
        material: "Organic Cotton",
        price: 640,
        originalPrice: 9600,
        condition: "Excellent",
        image: "/assets/men - sweatshirt.jpg",
        category: "For Him",
    },
    {
        name: "White Flared Pants",
        brand: "Zara",
        material: "Cotton",
        price: 720,
        originalPrice: 10400,
        condition: "Like New",
        image: "/assets/woman - White Flared Pants.jpg",
        category: "For Her",
    },
    {
        name: "Baggy Jeans",
        brand: "Mango",
        material: "Denim",
        price: 760,
        originalPrice: 11200,
        condition: "Excellent",
        image: "/assets/woman - baggy jeans.jpg",
        category: "For Her",
    },
    {
        name: "Crop Top",
        brand: "Forever 21",
        material: "Cotton",
        price: 280,
        originalPrice: 4000,
        condition: "Good",
        image: "/assets/woman - crop top.jpg",
        category: "For Her",
    },
    {
        name: "Jumpsuit",
        brand: "Mango",
        material: "Linen",
        price: 880,
        originalPrice: 12800,
        condition: "Like New",
        image: "/assets/woman - jumpsuits.jpg",
        category: "For Her",
    },
    {
        name: "Sundress",
        brand: "H&M",
        material: "Cotton",
        price: 680,
        originalPrice: 9600,
        condition: "Excellent",
        image: "/assets/woman - sundress.jpg",
        category: "For Her",
    },
    {
        name: "Sweater",
        brand: "Zara",
        material: "Wool",
        price: 800,
        originalPrice: 11200,
        condition: "Like New",
        image: "/assets/woman - sweaters.jpg",
        category: "For Her",
    },
    {
        name: "Polo Neck Hoodie",
        brand: "Nike",
        material: "Modal Cotton",
        price: 560,
        originalPrice: 8800,
        condition: "Good",
        image: "/assets/men - hoodie.jpg",
        category: "For Him",
    },
    {
        name: "Leather Biker Jacket",
        brand: "AllSaints",
        material: "Leather",
        price: 1120,
        originalPrice: 18000,
        condition: "Excellent",
        image: "/assets/men - jacket.jpg",
        category: "For Him",
    },
    {
        name: "Straight Fit Jeans",
        brand: "Levi's",
        material: "Denim",
        price: 720,
        originalPrice: 10400,
        condition: "Like New",
        image: "/assets/men - jeans.jpg",
        category: "For Him",
    },
    {
        name: "2- Piece Linen Suit",
        brand: "Hugo Boss",
        material: "Linen",
        price: 2800,
        originalPrice: 28000,
        condition: "Excellent",
        image: "/assets/men - linen suit.jpg",
        category: "For Him",
    },
    {
        name: "Popcorn T-Shirt",
        brand: "Zara",
        material: "Cotton",
        price: 440,
        originalPrice: 6400,
        condition: "Good",
        image: "/assets/men - polo shirt.jpg",
        category: "For Him",
    },
    {
        name: "Dungarees",
        brand: "Gap Kids",
        material: "Denim",
        price: 490,
        originalPrice: 8000,
        condition: "Excellent",
        image: "/assets/kids - dungrees.jpg",
        category: "Kids",
    },
    {
        name: "Girl's Frock",
        brand: "H&M Kids",
        material: "Cotton",
        price: 360,
        originalPrice: 5600,
        condition: "Like New",
        image: "/assets/kids - frock.jpg",
        category: "Kids",
    },
    {
        name: "Girl's Blue Cord Set",
        brand: "Zara Kids",
        material: "Cotton",
        price: 600,
        originalPrice: 8800,
        condition: "Like New",
        image: "/assets/kids - outfits.jpg",
        category: "Kids",
    },
    {
        name: "Bag",
        brand: "Coach",
        material: "Leather",
        price: 960,
        originalPrice: 14400,
        condition: "Good",
        image: "/assets/accesory - bag.jpg",
        category: "Accessories",
    },
    {
        name: "Bracelet Set",
        brand: "Accessorize",
        material: "Mixed Metals",
        price: 320,
        originalPrice: 4800,
        condition: "Like New",
        image: "/assets/accesory - bracelet sets.jpg",
        category: "Accessories",
    },
    {
        name: "Clutch",
        brand: "Mango",
        material: "PVC Plastic",
        price: 60,
        originalPrice: 9600,
        condition: "Excellent",
        image: "/assets/accesory - clutch.jpg",
        category: "Accessories",
    },
    {
        name: "Kurti",
        brand: "Fabindia",
        material: "Synthetic Blend",
        price: 880,
        originalPrice: 12800,
        condition: "Like New",
        image: "/assets/woman - kurti.jpg",
        category: "For Her",
    },
    {
        name: "Short Kurti",
        brand: "Global Desi",
        material: "Cotton",
        price: 680,
        originalPrice: 10400,
        condition: "Excellent",
        image: "/assets/woman - kurti2.jpg",
        category: "For Her",
    },
    {
        name: "Off-Shoulder Crop Top",
        brand: "Forever 21",
        material: "Cotton",
        price: 800,
        originalPrice: 11200,
        condition: "Like New",
        image: "/assets/woman - crop top1.jpg",
        category: "For Her",
    },
    {
        name: "Men's Ring",
        brand: "Tanishq",
        material: "Metal and Stone",
        price: 360,
        originalPrice: 5600,
        condition: "Excellent",
        image: "/assets/accesory - men ring.jpg",
        category: "Accessories",
    },
    {
        name: "Necklace",
        brand: "Tanishq",
        material: "Gold plated Silver",
        price: 600,
        originalPrice: 8800,
        condition: "Like New",
        image: "/assets/accesory - necklace.jpg",
        category: "Accessories",
    },
    {
        name: "Imitation Ring",
        brand: "Accessorize",
        material: "Silver",
        price: 400,
        originalPrice: 14400,
        condition: "Excellent",
        image: "/assets/accesory - ring.jpg",
        category: "Accessories",
    },
    {
        name: "Men's Wallet",
        brand: "Tommy Hilfiger",
        material: "Genuine Leather",
        price: 320,
        originalPrice: 4800,
        condition: "Good",
        image: "/assets/accesory - wallet.jpg",
        category: "Accessories",
    },
    {
        name: "Women's Leather Belt",
        brand: "Zara",
        material: "Genuine Leather",
        price: 640,
        originalPrice: 9600,
        condition: "Like New",
        image: "/assets/accesory - woman belt.jpg",
        category: "Accessories",
    },
    {
        name: "PJs Set",
        brand: "Gap Kids",
        material: "Pure Cotton",
        price: 360,
        originalPrice: 5600,
        condition: "Excellent",
        image: "/assets/kids - pjs.jpg",
        category: "Kids",
    },
    {
        name: "Boys Superhero Set",
        brand: "Marvel",
        material: "Synthetic Blend",
        price: 600,
        originalPrice: 8800,
        condition: "Like New",
        image: "/assets/kids - captain america.jpg",
        category: "Kids",
    },
];

const seed = async () => {
    console.log('Seeding database...');
    const { error } = await supabase
        .from('products')
        .insert(initialProducts);

    if (error) {
        console.error('Error seeding database:', error);
    } else {
        console.log('Database seeded successfully!');
    }
};

seed();
